apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: reviews-app
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: reviews-app
  type: NodePort