apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reviews-app-webserver
  namespace: galina-test
  labels:
    app: reviews-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews-app
    spec:
      containers:
      - image: atamankina/reviews:latest
        imagePullPolicy: Always
        name: reviews-app-webserver
        env:
          - name: FLASK_ENV
            value: development
          - name: POSTGRES_DB
            value: reviews
          - name: POSTGRES_USER
            value: galina
          - name: POSTGRES_PASSWORD
            value: password
          - name: POSTGRES_HOST
            value: reviews.cbzlvkulvgid.us-east-1.rds.amazonaws.com
        ports:
          - containerPort: 5000