apiVersion: v1
kind: Service
metadata:
  name: reviews-app-webserver
  namespace: galina-test
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: reviews-app
  type: LoadBalancer