apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: reviews-app-webserver
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: atamankina/reviews:latest
          env:
            - name: FLASK_ENV
              value: development
            - name: POSTGRES_DB
              value: reviews
            - name: POSTGRES_USER
              value: galina
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_HOST
              value: reviews.cbzlvkulvgid.us-east-1.rds.amazonaws.com