apiVersion: v1
kind: Service
metadata:
  name: reviews-app-webserver
  namespace: k8s-test
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: reviews-app
  type: LoadBalancer